/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controler.Controler;
import model.Calculadora;

/**
 * * @author Pedro Duarte e Thales Bastos
 * Professora: Luciana Campos
 * Laboratório de Programação de Computadores 2 - Qual é o resultado?
 */
public class view extends javax.swing.JPanel {

    /**
     * Creates new form view
     */
    public view() {

        setDefaultLocale(null);

        initComponents();
        initCalc();

    }

    public void initCalc() {
        Controler.num1 = Calculadora.randNum();
        Controler.num2 = Calculadora.randNum();
        Controler.opr = Calculadora.randOperator();
        this.numAleatorio1.setText(String.valueOf(Controler.num1));
        this.numAleatorio2.setText(String.valueOf(Controler.num2));
        this.Operador.setText(Controler.getOperator());
        this.Resultado.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        menuEnum = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        numAleatorio1 = new javax.swing.JLabel();
        Operador = new javax.swing.JLabel();
        Resultado = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        numAleatorio2 = new javax.swing.JLabel();
        separadorCaixa1 = new javax.swing.JSeparator();
        separadorCaixa2 = new javax.swing.JSeparator();
        separadorCaixa3 = new javax.swing.JSeparator();
        separadorCaixa5 = new javax.swing.JSeparator();
        separadorCaixa4 = new javax.swing.JSeparator();
        num1 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num7 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        num0 = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Tentar = new javax.swing.JButton();
        menos = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        pontos = new javax.swing.JLabel();
        passar = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        reiniciar = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setForeground(new java.awt.Color(236, 186, 177));
        setMaximumSize(new java.awt.Dimension(618, 512));
        setMinimumSize(new java.awt.Dimension(618, 512));
        setName(""); // NOI18N

        jLabel1.setText("Adivinhe o resultado da operação");

        numAleatorio1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        numAleatorio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numAleatorio1.setText("N1");

        Operador.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Operador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Operador.setText("operador");

        Resultado.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Resultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Resultado.setText("RESULTADO");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("=");

        numAleatorio2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        numAleatorio2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numAleatorio2.setText("N2");

        separadorCaixa1.setBackground(new java.awt.Color(40, 86, 117));
        separadorCaixa1.setForeground(new java.awt.Color(12, 31, 44));

        separadorCaixa2.setBackground(new java.awt.Color(40, 86, 117));
        separadorCaixa2.setForeground(new java.awt.Color(12, 31, 44));

        separadorCaixa3.setBackground(new java.awt.Color(40, 86, 117));
        separadorCaixa3.setForeground(new java.awt.Color(12, 31, 44));
        separadorCaixa3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        separadorCaixa5.setBackground(new java.awt.Color(40, 86, 117));
        separadorCaixa5.setForeground(new java.awt.Color(12, 31, 44));
        separadorCaixa5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        separadorCaixa4.setBackground(new java.awt.Color(40, 86, 117));
        separadorCaixa4.setForeground(new java.awt.Color(12, 31, 44));

        javax.swing.GroupLayout menuEnumLayout = new javax.swing.GroupLayout(menuEnum);
        menuEnum.setLayout(menuEnumLayout);
        menuEnumLayout.setHorizontalGroup(
            menuEnumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuEnumLayout.createSequentialGroup()
                .addGroup(menuEnumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuEnumLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(numAleatorio1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Operador, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numAleatorio2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menuEnumLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuEnumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuEnumLayout.createSequentialGroup()
                    .addContainerGap(203, Short.MAX_VALUE)
                    .addComponent(separadorCaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(menuEnumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuEnumLayout.createSequentialGroup()
                    .addComponent(separadorCaixa2, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(menuEnumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuEnumLayout.createSequentialGroup()
                    .addContainerGap(579, Short.MAX_VALUE)
                    .addComponent(separadorCaixa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(menuEnumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menuEnumLayout.createSequentialGroup()
                    .addComponent(separadorCaixa4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 573, Short.MAX_VALUE)))
            .addGroup(menuEnumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menuEnumLayout.createSequentialGroup()
                    .addComponent(separadorCaixa5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 585, Short.MAX_VALUE)))
        );
        menuEnumLayout.setVerticalGroup(
            menuEnumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuEnumLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(menuEnumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numAleatorio1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Operador, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numAleatorio2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 23, Short.MAX_VALUE))
            .addGroup(menuEnumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menuEnumLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(separadorCaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(87, Short.MAX_VALUE)))
            .addGroup(menuEnumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuEnumLayout.createSequentialGroup()
                    .addGap(0, 93, Short.MAX_VALUE)
                    .addComponent(separadorCaixa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(menuEnumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menuEnumLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(separadorCaixa3, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)))
            .addGroup(menuEnumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menuEnumLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(separadorCaixa4, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(87, Short.MAX_VALUE)))
            .addGroup(menuEnumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menuEnumLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(separadorCaixa5, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)))
        );

        num1.setText("1");
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });

        num3.setText("3");
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });

        num2.setText("2");
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });

        num6.setText("6");
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6ActionPerformed(evt);
            }
        });

        num9.setText("9");
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9ActionPerformed(evt);
            }
        });

        num5.setText("5");
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });

        num4.setText("4");
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });

        num7.setText("7");
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7ActionPerformed(evt);
            }
        });

        num8.setText("8");
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8ActionPerformed(evt);
            }
        });

        num0.setText("0");
        num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num0ActionPerformed(evt);
            }
        });

        Delete.setText("DEL");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Tentar.setText("Tentar");
        Tentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TentarActionPerformed(evt);
            }
        });

        menos.setText("-");
        menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(236, 186, 177));

        jSeparator2.setForeground(new java.awt.Color(236, 186, 177));

        pontos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        pontos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pontos.setText("Pontuacao :  0");

        passar.setText("Passar");
        passar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passarActionPerformed(evt);
            }
        });

        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        reiniciar.setText("Reiniciar");
        reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(pontos, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(passar)
                .addGap(30, 30, 30)
                .addComponent(reiniciar)
                .addGap(30, 30, 30)
                .addComponent(sair, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {passar, reiniciar, sair});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pontos)
                    .addComponent(passar)
                    .addComponent(sair, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reiniciar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {passar, reiniciar, sair});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Tentar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(num4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(24, 24, 24)
                                                .addComponent(num5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(num7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(num0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(24, 24, 24)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(menos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(num8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(num9, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                            .addComponent(num6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))))
                                .addGap(4, 4, 4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(menuEnum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2))))
                .addGap(15, 15, 15))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {menos, num0, num4, num5, num6, num7, num8, num9});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(menuEnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num1)
                    .addComponent(num2)
                    .addComponent(num3))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num4)
                    .addComponent(num5)
                    .addComponent(num6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num8)
                    .addComponent(num7)
                    .addComponent(num9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(num0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(Tentar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Delete, Tentar, num0, num1, num2, num3, num4, num5, num6, num7, num8, num9});

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        if (this.Resultado.getText().equals("0")) {
            this.Resultado.setText("");
        }

        this.Resultado.setText(this.Resultado.getText() + "1");
    }//GEN-LAST:event_num1ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        if (this.Resultado.getText().equals("0")) {
            this.Resultado.setText("");
        }
        this.Resultado.setText(this.Resultado.getText() + "4");
    }//GEN-LAST:event_num4ActionPerformed

    private void num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num7ActionPerformed
        if (this.Resultado.getText().equals("0")) {
            this.Resultado.setText("");
        }
        this.Resultado.setText(this.Resultado.getText() + "7");
    }//GEN-LAST:event_num7ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        if (this.Resultado.getText().equals("0")) {
            this.Resultado.setText("");
        }
        this.Resultado.setText(this.Resultado.getText() + "5");
    }//GEN-LAST:event_num5ActionPerformed


    private void num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8ActionPerformed
        if (this.Resultado.getText().equals("0")) {
            this.Resultado.setText("");
        }
        this.Resultado.setText(this.Resultado.getText() + "8");
    }//GEN-LAST:event_num8ActionPerformed

    private void num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num0ActionPerformed
        if (this.Resultado.getText().equals("0") && !this.Resultado.equals("-")) {
            this.Resultado.setText("");
        }
        this.Resultado.setText(this.Resultado.getText() + "0");
    }//GEN-LAST:event_num0ActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        this.Resultado.setText(Controler.delete(this.Resultado.getText()));
    }//GEN-LAST:event_DeleteActionPerformed

    private void num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num6ActionPerformed
        if (this.Resultado.getText().equals("0") || this.Resultado.getText().equals("")) {
            this.Resultado.setText("");
        }
        this.Resultado.setText(this.Resultado.getText() + "6");
    }//GEN-LAST:event_num6ActionPerformed

    private void reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarActionPerformed
        controler.Controler.reiniciar();
        this.pontos.setText("Resultado: " + Controler.pontos);
        this.numAleatorio1.setText(String.valueOf(Controler.num1));
        this.numAleatorio2.setText(String.valueOf(Controler.num2));
        this.Operador.setText(Controler.getOperator());
        this.Resultado.setText("0");
    }//GEN-LAST:event_reiniciarActionPerformed

    private void passarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passarActionPerformed
        controler.Controler.passar();
        this.numAleatorio1.setText(String.valueOf(Controler.num1));
        this.numAleatorio2.setText(String.valueOf(Controler.num2));
        this.Operador.setText(Controler.getOperator());
        this.Resultado.setText("0");
    }//GEN-LAST:event_passarActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        System.exit(3);
    }//GEN-LAST:event_sairActionPerformed

    private void TentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TentarActionPerformed
        controler.Controler.enviarTentativa(this.Resultado.getText());
        this.pontos.setText("Resultado: " + Controler.pontos);

        controler.Controler.passar();
        this.numAleatorio1.setText(String.valueOf(Controler.num1));
        this.numAleatorio2.setText(String.valueOf(Controler.num2));
        this.Operador.setText(Controler.getOperator());
        this.Resultado.setText("0");
    }//GEN-LAST:event_TentarActionPerformed

    private void menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosActionPerformed
        if (this.Resultado.getText().equals("0") || this.Resultado.getText().equals(null)) {

            this.Resultado.setText("-");
        }

    }//GEN-LAST:event_menosActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed

        if (this.Resultado.getText().equals("0")) {
            this.Resultado.setText("");
        }
        this.Resultado.setText(this.Resultado.getText() + "3");

    }//GEN-LAST:event_num3ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        if (this.Resultado.getText().equals("0")) {
            this.Resultado.setText("");
        }
        this.Resultado.setText(this.Resultado.getText() + "2");
    }//GEN-LAST:event_num2ActionPerformed

    private void num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num9ActionPerformed
        if (this.Resultado.getText().equals("0")) {
            this.Resultado.setText("");
        }
        this.Resultado.setText(this.Resultado.getText() + "9");
    }//GEN-LAST:event_num9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JLabel Operador;
    private javax.swing.JLabel Resultado;
    private javax.swing.JButton Tentar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton menos;
    private javax.swing.JPanel menuEnum;
    private javax.swing.JButton num0;
    private javax.swing.JButton num1;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JLabel numAleatorio1;
    private javax.swing.JLabel numAleatorio2;
    private javax.swing.JButton passar;
    private javax.swing.JLabel pontos;
    private javax.swing.JButton reiniciar;
    private javax.swing.JButton sair;
    private javax.swing.JSeparator separadorCaixa1;
    private javax.swing.JSeparator separadorCaixa2;
    private javax.swing.JSeparator separadorCaixa3;
    private javax.swing.JSeparator separadorCaixa4;
    private javax.swing.JSeparator separadorCaixa5;
    // End of variables declaration//GEN-END:variables
}
